### ISSUE TITLE
Themes keep getting deleted

### ISSUE THREAD

**Issue by JaneJeon** [SNathJr/ghost-on-heroku#13]
Hi, I host this on free plan heroku, which means it goes to sleep.

I had a blog working with this before yesterday's updates, but now that I updated the blog, Heroku seems to delete ALL of Ghost's themes every time it goes to sleep.

The only thing that changed was the code, so I'm guessing it's probably this commit - https://github.com/SNathJr/ghost-on-heroku/commit/3e40b8da2feed8e2ee81bee90737bcc62bcee6c9 - that broke it.

Oh, and I should mention - one of the blog uses the default casper theme (with newest version of ghost-on-heroku), and that one doesn't break even on sleep, however the other one uses the London theme (which I upload via zip to install) and when I do that, it works... until it sleeps and deletes the theme (in fact, when it wakes up it says "no theme installed!")

edit: on further investigation, it seems to be an issue with heroku and symlinks? https://stackoverflow.com/questions/10462787/how-do-i-use-npm-link-with-heroku because when I run heroku run ls content/themes, it shows the 5 "installed" themes, but when I boot it up none of the themes are there!

update: `npm link` didn't help, either...

**Comment by JaneJeon** [comment]
Update update: I realize that this is similar to #9, but my problem is that I don't even see the "default" themes that should be installed via node_modules - casper, london, attilla, etc! They're all gone after a sleep... 😱

**Comment by JaneJeon** [comment]
From what I can tell, the only way to get this to work on heroku is to actually include node_modules and not gitignore it...

It feels so, so, _so_ dirty, but it seems to be the only way @SNathJr

**Comment by SNathJr** [comment]
@JaneJeon sounds like a fix, though it will be a dirty one. Also, when building from source the Heroku Dyno should generate this folder by default. Let me investigate it further. Will try to push some update later today.

Thanks!
