### ISSUE TITLE
Running Ghost Locally?

### ISSUE THREAD

**Issue by bhellman1** [SNathJr/ghost-on-heroku#19]
Thank you for creating this repo! Is it possible to run Ghost locally using their CLI like so: `ghost start`

If you install the CLI and try to start Ghost:

`Working directory is not a recognisable Ghost installation`

Thanks

**Comment by alexthewilde** [comment]
same issue here.

**Comment by alexthewilde** [comment]
Here's how got this working:

1. Create another ghost installation locally
2. Copy `.ghost-cli` and the `versions` directory into ghost-on-heroku folder
3. Go into your ghost-on-heroku folder and create a symlink `current` to `versions/3.1.0`
4. Verify with `ghost start`
