### ISSUE TITLE
Internal Server Error on Image upload to S3

### ISSUE THREAD

**Issue by ankittaneja** [SNathJr/ghost-on-heroku#22]
Hi @SNathJr 

Nice work with maintaining this package. 

I just deployed it to Heroku with S3. Initially I was getting Resource Not Found as I named the bucket incorrectly in config var, but now I am getting 'Internal Server Error, cannot upload image' 

What can be the issue? I have double checked all vars.

Also, until you figure out #9 , Perhaps add steps for people on how to add (paid) theme to themes folder and then commit & deploy.

Thanks.

**Comment by ankittaneja** [comment]
I am getting Access Denied in Logs for uploading, I have given AMAZONS3FULLACCESS permission. When S3 is removed, works fine. Must be a problem in my access credentials. Will check.

**Comment by arturojain** [comment]
what was the solution in this case?

**Comment by mehulmpt** [comment]
Faced a similar issue. The fix was to make bucket publicly accessible in AWS bucket settings.

**Comment by cancan101** [comment]
Is there a solution to this problem that uses IAM rather than bucket settings?
