### ISSUE TITLE
Local image files are not uploading 

### ISSUE THREAD

**Issue by imballa** [SNathJr/ghost-on-heroku#23]
I have configured aws s3 & even cloudinary, but images are not uploading from local.

**Comment by SNathJr** [comment]
Hi @imballa 

The process is either configure AWS S3 or Cloudinary. Local file upload should work just fine.

FYI: As of the latest state of this repository, if you just set app url and leave everything as is, everything should work fine.

**Comment by SNathJr** [comment]
@imballa 

I will be closing this issue as there is no response from the OP. If you need any further help feel free to reopen and comment.

Cheers!
