### ISSUE TITLE
NGINX 502 Error. Bad Gateway

### ISSUE THREAD

**Issue by drxos** [SNathJr/ghost-on-heroku#25]
Hi.

I'm trying to deploy Ghost. But I got an error according to the Database connection. I'm using PostgreSQL Database with 
```
DATABASE_URL=postgres://postgres:SOME_PASSWORD@dokku-postgres-lolipop:5432/lolipop
```
So I extracted host, user, password, database from this DATABASE_URL without success.

How do I fix it ?

**Comment by JaneJeon** [comment]
not quite sure what the question is. The connection string looks okay, but just make sure that you can connect to postgres with your credentials from the CLI (`user:postgres, password:SOME_PASSWORD, database location: dokku-postgres-lolipop:5432, database: lolipop`).

For how to do it, I suggest that you look up how to connect using `psql`.

**Comment by drxos** [comment]
Helle @JaneJeon 

It's ok for me. I set environment variable for those credentials.

Unfortunately, I'm facing another issue. I'm goting 502 error Bad Gateway.

**Comment by JaneJeon** [comment]
Well, 502 just means that upstream server (in this case, your Heroku Ghost server) has an error.

I suggest you look at the logs to try to point what might've gone wrong, as there's nothing we can do from our end.

**Comment by drxos** [comment]
> Well, 502 just means that upstream server (in this case, your Heroku Ghost server) has an error.
> 
> I suggest you look at the logs to try to point what might've gone wrong, as there's nothing we can do from our end.

Hey @JaneJeon 

I did it and got this output:

```
ghost-on-heroku@3.0.0 start /app
[2019-12-06 00:06:18] INFO Ghost is running in production...
[2019-12-06 00:06:18] INFO Your site is now available on https://xxxxxx.xx/
[2019-12-06 00:06:18] INFO Ctrl+C to shut down
```
I added you, the environment variables I set last time in order to make it deploy:

```
database__client:               mysql
database__connection__database: chameleon
database__connection__host:     dokku-mysql-chameleon
database__connection__password: 2d05eeb9d1697699
database__connection__port:     3306
database__connection__user:     mysql
url:                            https://xxxxxx.xx/

```
What's really  wrong with it ?

**Comment by JaneJeon** [comment]
Do you not have `DATABASE_URL`? Now that I think about it, Ghost doesn't work with Postgres, so if you were using an addon, it should've added `DATABASE_URL` to your environment variable.

**Comment by drxos** [comment]
> Do you not have `DATABASE_URL`? Now that I think about it, Ghost doesn't work with Postgres, so if you were using an addon, it should've added `DATABASE_URL` to your environment variable.

I'm not use anymore Postgres. And I have DATABASE_URL in the environment as usual.

**Comment by JaneJeon** [comment]
And that `DATABASE_URL` is for the mysql db?

**Comment by drxos** [comment]
> And that `DATABASE_URL` is for the mysql db?

Yes

**Comment by SNathJr** [comment]
Hi @drxos 

Could you once again explain your process of hosting Ghost? Are you deploying from a local environment or are you deploying from this repository?

**Comment by SNathJr** [comment]
@drxos 

Will be closing this issue as there is no response from the OP. If you need any further help, feel free to reopen and comment.

Cheers!
