### ISSUE TITLE
Issue with using Cloudinary after deploy from GitHub

### ISSUE THREAD

**Issue by mattcam** [SNathJr/ghost-on-heroku#26]
Would be helpful to confirm if others are having same issue or if this is just to do with the deployment process that I am using. In summary these are the step when deploying:

1. Create an empty repository for new website.
2. Clone this repository to local.
3. Copy the contents of the cloned repository to the empty repository.
4. And then commit.

Issue occurs where after the website is deployed from GitHub then unable to use app because it fails with this issue.

```

/app/content/adapters/storage/ghost-storage-cloudinary:1
../../../node_modules/ghost-storage-cloudinary/
^

SyntaxError: Unexpected token .

```

Notes:

1. Cloudinary works as expected until the first deploy from GitHub.
2. This issue has only just started occurring.
3. Downgrade Ghost to 3.0.3 does not resolve.
4. The issue occurs when using https://github.com/SNathJr/ghost-on-heroku/commit/1a897f8c6888dc8362bbd1d0e22aa9e43aa7b44d on Heroku stack heroku-18
5. Only way to conitnue using app is to remove `CLOUDINARY_URL`.
6. Also experiencing a similar issue with s3.

**Comment by JaneJeon** [comment]
So from what it looks like, it seems like the symlink at https://github.com/SNathJr/ghost-on-heroku/tree/master/content/adapters/storage is failing to actually reach into `node_modules` when deployed to Heroku.

Heroku's file system storage can be finnicky - have you tried running `npm install --production` command on Heroku? I just want to make sure there _is_ anything in `node_modules` at all to begin with.

**Comment by mattcam** [comment]
Thanks for the very helpful guidance, found that my deployment process was removing the symlink.

To resolve I changed my deployment process to the following:

1. clone this repository.
2. change the origin.
3. and then proceed with any theme edits and deployment via GitHub.

Previously the copy removed the symlink.

Note that I am doing this on Windows 10.
