### ISSUE TITLE
Scheduled Posts Never Go Live

### ISSUE THREAD

**Issue by bhellman1** [SNathJr/ghost-on-heroku#27]
Hello! Scheduled posts used to work with Ghost 2.0 on Heroku - Since upgrading to Ghost 3.0.0 and later 3.2.0 scheduled posts never go live and cause an error (see below).

Is this a known issue? Any suggestions on how to get scheduled posts working on Heroku? Thanks!

**Error Message via
<img width="1169" alt="Screen Shot 2019-12-19 at 11 44 53 AM" src="https://user-images.githubusercontent.com/298219/71204763-c9b70200-2255-11ea-91a3-ba16cfbba96c.png">
 the Heroku Logs**

**Comment by JaneJeon** [comment]
Have you asked the official Ghost repo about this? Have you tried to replicate this locally?

If upgrading from Ghost 2 to 3 is what broke your scheduled posts, I have a hunch that it most likely has to do with Ghost, not this repo.

**Comment by SNathJr** [comment]
@bhellman1 

Is there any update on the status of this problem?

Thanks
