### ISSUE TITLE
Suggestion to make it clear on your readme what Ghost version exactly this packages. Ghost is now on version 3.2.0

### ISSUE THREAD

**Issue by codechair** [SNathJr/ghost-on-heroku#29]
Hi again,

Just a suggestion to make it clear on your readme what Ghost version exactly this packages. Ghost is now on version 3.2.0

Alternatively, where can I check the version of Ghost in your files (is your version now on 3.0.0)?

Thanks a ton

**Comment by SNathJr** [comment]
Hey @codechair ,

Thanks for the suggestion, will surely update Readme to be more clear.

You can also check the same in releases or package.json

Regards!
SNathJr
