### ISSUE TITLE
Changing repository in app.json and in package.json to my fork of this repo makes heroku not deploy

### ISSUE THREAD

**Issue by codepar** [SNathJr/ghost-on-heroku#32]
Hi Swastik

This is a great contribution, so thanks for this!

I'm trying to understand how things work in this deployment to Heroku but not luck (trying to understand whether I'll be able to maintain things myself going forward)

When I fork your repo and change the repository in app.json and in package.json to my fork of this repo makes Heroku not deploy, I get an error in the script and scaling dynos phase. Why? Why can't I use my own repo (fork from yours)?

Everything works though if I push your deploy to Heroku button on your repo.

My intention with this question is to understand things further ahead of blindly building my blog on something I'm not fully understanding :) Hope this is ok.

**Comment by JaneJeon** [comment]
Changing the repository in `app.json` actually shouldn't affect the deployment, because Heroku normally gets your repository URL from the "referrer" attribute when you click the "Deploy to Heroku" button.

package.json would also not affect the deployment, because it's purely for a metadata reason.

In fact, the issue is this in the README:
```
[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy?template=https://github.com/snathjr/ghost-on-heroku)
```

So this repository is hardcoded into the button even though it doesn't have to. I'll make a PR for that to fix this.

**Comment by codepar** [comment]
Hi @JaneJeon and @SNathJr Thanks for the inputs.

Sadly, this didn't work.

This repo right now actually does not deploy at all., for no one when clicking on the deploy button `(The given URL (https://heroku.com/) is not a valid GitHub repository.) `See image 

<img width="834" alt="Screenshot 2020-01-11 at 13 04 34" src="https://user-images.githubusercontent.com/42570159/72204724-f506c880-3472-11ea-8c4f-93444dd6576b.png">

I've then tried to do the following:

1. fork
2. Change repository in app.json
3. Change repository in package.json
4. Change the template in the button from [![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy?template=https://github.com/snathjr/ghost-on-heroku) to my repo
5. I'm back to square zero. The deployment passes the build app phase but I get errors on "Run scripts & scale dynos"

<img width="834" alt="Screenshot 2020-01-11 at 13 08 18" src="https://user-images.githubusercontent.com/42570159/72204804-dc4ae280-3473-11ea-94dc-d428f8955630.png">

So at this stage, no one can essentially make this work by simply clicking on the deploy button on this repo
Nor, since previously, could they fork and adjust the deployment to their own repo.

Pointers more than welcome.

**Comment by JaneJeon** [comment]
Nope, it works for me.
I just tried forking this repo to my personal account and clicked on "Deploy to Heroku" WITHOUT changing anything.
And BAM! Instantly I got this: https://i.imgur.com/2ntnCH8.png and it succeeded without any hitch: https://i.imgur.com/JFp6POF.png
So clearly the problem **ISN'T** with forking on its own, but rather what you're doing to it.
As there's nothing wrong with the repository itself nor the act of forking, I recommend that this issue remain closed.

**Comment by SNathJr** [comment]
@JaneJeon @codepar 

I confirm that there is a problem. It does not work when you have ad blockers and antivirus shields.

**Comment by JaneJeon** [comment]
@SNathJr what adblocker are you using? I have uBlock Origin and I have basically every filter turned on, and even _that_ doesn't break heroku...

**Comment by SNathJr** [comment]
@JaneJeon I am using Brave browser's default shield (that has an ad-block inbuilt), it seems to break heroku's ability to refer origin.

**Comment by JaneJeon** [comment]
@SNathJr wow that's nuts. So our code isn't wrong, but I guess it can't hurt to add a little disclaimer at the bottom about using this repo with an overzealous blocker.

**Comment by SNathJr** [comment]
@JaneJeon Yep, absolutely. I have made a recent commit with a hardcoded link, so if anyone fails to deploy with the deploy button, they can try the link.

**Comment by codepar** [comment]
Thanks both! @JaneJeon  and @SNathJr 

Following up.

Confirmed that the below was solved by putting shields down on Brave (yes, I was using brave) or simply using Chrome solved the issue: https://user-images.githubusercontent.com/42570159/72204724-f506c880-3472-11ea-8c4f-93444dd6576b.png

So that is sorted, it had to do with an overzealous browser as @JaneJeon mentioned.

However, this does not explain why I cannot release the dependency of this repository by changing the repo in app.json and in package.json in my own fork (to clarify here @JaneJeon, I was not using an old repo when I've opened the issue, what you saw was one of several repos that I've deleted while trying things out, the latest (which I had used for the screenshots) had been deleted when I've checked).

So to replicate the issue I'm facing:
1. fork
2. Change repository in app.json (again, reason I am doing it is to release my repo of dependencies from this repo)
3. Change repository in package.json (again, reason I am doing it is to release my repo of dependencies from this repo)
4. Make sure not to be using an overzealous browser
5. Click the deploy button.
6. The deployment passes the build app phase but I get errors on "Run scripts & scale dynos"

This is the result again

https://user-images.githubusercontent.com/42570159/72204804-dc4ae280-3473-11ea-94dc-d428f8955630.png

So there are some other dependencies I can't point out when I read your code.

Again, pointers welcome. And sorry for the back and forth, but I'm sure others trying to release their repo from dependencies with face the same issue.

Thanks once again!

**Comment by codepar** [comment]
Thanks both! @JaneJeon  and @SNathJr 

Following up, also for the sake of others in the future.

Confirmed that the below was solved by putting shields down on Brave (yes, I was using brave) or simply using Chrome solved the issue: https://user-images.githubusercontent.com/42570159/72204724-f506c880-3472-11ea-8c4f-93444dd6576b.png

So that is sorted, it had to do with an overzealous browser as @JaneJeon mentioned.

However, this didn't explain why I could release the dependency of this repository by changing the repo in app.json and in package.json in my own fork (to clarify here @JaneJeon, I was not using an old repo when I've opened the issue, what you saw was one of several repos that I've deleted while trying things out, the latest (which I had used for the screenshots) had been deleted when I've checked).

So to replicate the issue I'm facing:
1. Download files (not simply fork) and place contents in a new repository (thus, not branched from this one)
2. Change repository in app.json (again, reason I am doing it is to release my repo of dependencies from this repo)
3. Change repository in package.json (again, reason I am doing it is to release my repo of dependencies from this repo)
4. Make sure not to be using an overzealous browser
5. Click the deploy button.
6. The deployment passes the build app phase but I get errors on "Run scripts & scale dynos"

Or simply click deploy on the repo I've created (result of the download of the code in the fork)
https://github.com/codepar/test-ghost-heroku

This is the result again

https://user-images.githubusercontent.com/42570159/72204804-dc4ae280-3473-11ea-94dc-d428f8955630.png

So there are some other dependencies I can't point out when I read your code. There is something about this only working when this is a fork of this repo, but not if code is downloaded. Then this might be me and my knowledge of git lacking (so apologies if so) :) 

Again, pointers welcome. And sorry for the back and forth, but I'm sure others trying to release their repo from dependencies with face the same issue.

Thanks once again!

**Comment by JaneJeon** [comment]
Again, app.json and package.json repository URLs are only relevant as metadata. The _only_ thing that actually sets the repository URL is the links attached to the heroku button, and as we have seen, we confirm that it’s working.

So the error you’re getting is that you can’t connect to MySQL. Have you added your credit card information to your heroku account? As I recall, basically any third party add on won’t work without payment details in your heroku account.

**Comment by codepar** [comment]
Thanks for reverting Jane.

Sorry for not making it clear.

If I click deploy on a fork, it deploys. all 100% OK. This is the fork: https://github.com/codepar/ghost-on-heroku

If I click deploy on a repo with downloaded code from your repo, it doesn't. This is the repo with the downloaded code: https://github.com/codepar/test-ghost-heroku (You can click the "deploy" button yourself to test)

Both have the "metadata" changed, both are deploying to the same heroku account. The only difference is that one is a fork, the other is downloaded code from your repo. 

So, given this is not about my Heroku account or added credit card, given it deploys... would you have other pointers?

Thanks a lot once again!

**Comment by JaneJeon** [comment]
We’ve seen people have trouble with _downloaded_ and/or copied versions of this repo as we rely on symlinks.

I heavily suggest that you use forks or clones as it gets automatically updated and you can push newer versions to heroku with fit.

@snathjr I think we should explicitly drop support for downloaded or copied repos because honestly, how many issues have you seen that was because people were downloading the repo? Only forks and clones should be officially supported. We shouldn’t be tech support for people being afraid of git :/

**Comment by SNathJr** [comment]
@JaneJeon agreed!

@codepar please use a fork and commit your changes there. Then you could deploy to heroku directly.

Cheers!

**Comment by JaneJeon** [comment]
@SNathJr should you or I make the PR? I'm currently at work but I can draft some changes during lunch.

**Comment by SNathJr** [comment]
@JaneJeon It would be a huge help from you, if you could do a PR.

Thanks

**Comment by codepar** [comment]
thanks both for making that clear now in the repo
