### ISSUE TITLE
Change the "from address" for transactional emails

### ISSUE THREAD

**Issue by codechair** [SNathJr/ghost-on-heroku#37]
**Is your feature request related to a problem? Please describe.**
I'm frustrated to have transactional emails coming from `noreply@mydomain.com`. When running a blog, nowadays, one is not supposed to push people away with a "no reply", but to welcome them

Also, one should not be using their main domain to send out transactional emails, but a subdomain like `alerts.mydomain.com`, given this would protect the reputation of their main email `mydomain.com`

**Describe the solution you'd like**
Change the "from address" for transactional emails from `noreply@mydomain.com` to for instance: `hello@mydomain.com`

Even better:
Change the "from address" for transactional emails from `noreply@mydomain.com` to for instance: `hello@alerts.mydomain.com` <-- this (adding a subdomain) is OPTIMAL

**Describe alternatives you've considered**
This seems to be possible by changing the configuration in `config.production.json`
[see ghost docs](https://ghost.org/docs/concepts/config/#from-address
)

One however can't change that inside heroku given its ephemeral filesystem, this setting has not been surfaced inside config vars in Heroku's settings, so unsure what to do

When it comes adding a subdomain, I have no idea even if a change in `config.production.json` would work, so surfacing the variables in Heroku's config vars may or may not help... but again, this would be the optimal solution for this feature request

**Additional context**
Once again, being able to add a subdomain would be optimal.

**Comment by JaneJeon** [comment]
https://ghost.org/docs/concepts/config/#running-ghost-with-config-env-variables

So set `mail__from='hello@mydomain.com'` in your environment variable to override it.

@SNathJr this should be closed.

**Comment by codechair** [comment]
@JaneJeon to clarify, is the direct the link you refer to this: https://ghost.org/docs/concepts/config/#from-address ?

And to touch what you've mentioned, to be very specific, do you mean 

1) changing `config.development.json`

and add `"from": "hello@mydomain.com",` ?

i.e. from this: 
```
"mail": {
    "transport": "Direct"
  },
```

to this:
"mail": {
    "transport": "Direct",
    "from": "hello@mydomain.com"
  },
```
?
Will this then propagate to `config.production.json` in some way?

or do you mean

2) adding a new config var to heroku settings tab? i.e. a key value pair with key = `"mail__from"` and value `'hello@mydomain.com'`

or 3) do you mean something else by environment variables?

-------

And to push it nudge, how to implement sending from a subdomain: i.e. : `hello@alerts.mydomain.com

`

**Comment by JaneJeon** [comment]
No, the link I’m referring to is correct. You can override config with environment variables, so I’m telling you to override the from address if you want by setting the end variable as I instructed.

**Comment by codechair** [comment]
I can now see the from address `hello@mydomain.com` in `config.production.json ` so it "may" work, but I can't test now because of another issue:

My issue now is : How to connect a Mailgun direct account to Heroku (i.e. deleting the Mailgun add-on)? I've created a separate issue for this https://github.com/SNathJr/ghost-on-heroku/issues/38
