### ISSUE TITLE
How to set up a "direct access" Mailgun account? (i.e. delete the Mailgun Heroku add-on)

### ISSUE THREAD

**Issue by codechair** [SNathJr/ghost-on-heroku#38]
**Describe the bug**
Ghost does not send emails because it needs a proper domain (non-sandbox) added to Mailgun. The Heroku Mailgun add-on does not allow domains to be added . And following a thread of several back and forth emails with Mailgun, it will not be possible to add domains to the Mailgun account created by Heroku. One needs to upgrade and pay some 19USD/month to be able to do so.

A Mailgun account created directly (i.e. going to their website, etc), however, allows domains to be created. So, with that in place, life could be good again :)

So, how can I set up a "direct access" Mailgun account inside Heroku (and subsequently delete the Heroku mailgun add-on)?

**To Reproduce**

1. Deploy your blog to a custom domain
2. Go to Ghost admin and turn on "members" inside labs
3. Pick an appropriate theme, e.g. Lyra
4. Try to subscribe on your ghost blog, by entering an email address
5. get “Please enter a valid email address!”

**Expected behavior**
Ghost sends out emails 

**How are you deploying this?**
One-click deploy from fork

**Additional context**

**Comment by SNathJr** [comment]
@codechair Does #4 solve your issue?

**Comment by codechair** [comment]
Thanks for reverting @SNathJr  Had seen that issue before opening this one.

My back and forth with Mailgun is now on it's tenth email...

State as of now: There is not way of making the Mailgun Heroku add-on work in a proper blog.

In https://github.com/SNathJr/ghost-on-heroku/issues/4 you've mentioned: "If you also want to get a custom email id through mailgun, you need to verify your account via mailgun customer support."

This is what I've been trying and sadly, no, it is not possible to add a custom domain and (essentially) be able to have any email sent out by Ghost. To do that one needs to pay $19/month (if using Heroku Mailgun add-on).

State as of now: No email is sent out if mail-sending is implemented via this deployment.

So, to fix this: 

1. One needs to create a mailgun account directly (i.e. going to their website, etc). Then one can create domains directly. So, with that in place, life could be good again :)

2. Adjust the heroku config to read from that separate mailgun account (somehow) and this is what this issue is about.

 **how can I set up a "direct access" Mailgun account inside Heroku (and subsequently delete the Heroku mailgun add-on, even should I delete the Heroku mailgun add-on)?**

Thanks in advance once again for pointers @SNathJr

**Comment by SNathJr** [comment]
@codechair Okay, in that case, you could either create a new mailgun account and add the environmental variables in Heroku app's config vars; or you could convert the sandbox account to your personal account by providing details, such as email id (I suppose). Then, verify your domain with mailgun. 
I hope this helps, would love to know any update from your end.

Cheers!
SNathJr

**Comment by codechair** [comment]
Thanks @SNathJr 

This is now fixed.

For others in the future: According to mailgun you cannot convert the Heroku Mailgun add-on to a stand-alone (you can do that for other mailgun add-ons on other platforms - like hackspace for instance, but not on Heroku)

So, the solution is to create a mailgun account separately and change the settings inside heroku to point to the standalone account.

I have not, however, deleted the add-on and don’t know if I should or whether that would break sth else despite this not being (I guess) used?

Thanks again @SNathJr

**Comment by SNathJr** [comment]
@codechair 

Thanks for confirming. You can go ahead and delete your old mailgun add on (only after updating the new one's configurations in config vars).

Cheers!
SNathJr
