### ISSUE TITLE
How to remove Mailgun from the list of addons

### ISSUE THREAD

**Issue by anis-coding** [SNathJr/ghost-on-heroku#39]
When I try to deploy ghost on my heroku account it tells me that I need further verification, which I'm unable to make because Horeku doesn't accept my phone number unfortunately : https://tools.heroku.support/addons-verification

Even though I've added a credit card to my account so it's a verified account. 

How can I remove Mailgun from the template completely  (Email is not that important in my case), I tried to remove it from app.json in a fork but with no success.

I've been trying to install ghost on heroku for more than a week with no success at all :/

**Comment by SNathJr** [comment]
@anis-coding As of my experience, just providing a credit/debit card does the job. Also, I don't think to remove mailgun is such a good idea (imagine you have forgotten your password, etc.)

However, if you still want to remove it, you need to edit all the files that have mailgun settings and / or mailgun as dependencies: such as `app.json` and `bin/create-config` files.

Hope this helps.
SNathJr
