### ISSUE TITLE
How to configure email SMTP service?

### ISSUE THREAD

**Issue by valentierra** [SNathJr/ghost-on-heroku#4]
Hello there!

I had unsuccessfully tried to configure email SMTP service to invite collaborators but it seems it is not under Ghost but Heroku's domain.

Has someone achieved to send email invitations using this repo?

Thanks in advance!

**Comment by SNathJr** [comment]
Hi,

In heroku dashboard, click your app and go to the resources section. There you will see mailgun addon. You can click there to go to mailgun's dashboard. By default, mailgun provides a sandbox account (it can only send emails to pre-verified email accounts). If you wish to send emails, either verify the email addresses you wish to invite. (you can do so by adding authorized recipients in mailgun dashboard).

If you also want to get a custom email id through mailgun, you need to verify your account via mailgun customer support.

**Comment by valentierra** [comment]
Hi SNathJr

Impeccable. Thanks for the explanation and all the effort put on developing this project. It is really much appreciated.

Cheers

**Comment by antonioalmeida** [comment]
Hey @SNathJr 

One of the first use cases prompted when an instance of Ghost is created is whether or not you want to invite _collaborators_. 
It doesn't work because the email is not setup straight away.

It would be helpful if the solution you provided to this issue was on the repository's README. Skips an extra headache.

**Comment by SNathJr** [comment]
Hi @antonioalmeida 

Thank you for your suggestion. Now a quick setup note is available in the readme section. Please refer https://github.com/SNathJr/ghost-on-heroku/blob/master/README.md#setting-up-smtp-service for the same. Cheers!
