### ISSUE TITLE
Liebling theme is not working properly

### ISSUE THREAD

**Issue by keyuls** [SNathJr/ghost-on-heroku#42]
I am trying to use ghost theme [liebling](https://github.com/eddiesigner/liebling)

In _package.json_ , added

`liebling": "github:eddiesigner/liebling#v.0.6.4,
`

In _copy-themes.sh_ file, added
`liebling
`

After new push,  it shows the theme in the installed theme list:
![image](https://user-images.githubusercontent.com/8844721/72853316-4894c580-3c6e-11ea-9d19-3d005137f32a.png)

but when I activate it, it doesn't display correctly on the blog and it shows errors in the console:
![image](https://user-images.githubusercontent.com/8844721/72853388-80037200-3c6e-11ea-99e6-1b082781c4df.png)

This is happening only with the Liebling theme. All other themes are working properly.

Any suggestions on how to fix it?

**Comment by JaneJeon** [comment]
Do you get any errors on the server side?
