### ISSUE TITLE
Can't update theme, changes to *.hbs files do not render consistently

### ISSUE THREAD

**Issue by codechair** [SNathJr/ghost-on-heroku#44]
**Describe the bug**
I cannot update the theme (nothing at all, not even a simple removal of the link to Facebook on footer).

**To Reproduce**
1. Fork this repo, let's call the fork "Ghostified"
2. Fork the theme https://github.com/TryGhost/Lyra, let's call that fork "GhostifiedTheme"
3. Do first changes like adjusting the footer removing the facebook link (just comment out line 35 in `default.hbs`) in "GhostifiedTheme"
4. Commit changes to "GhostifiedTheme"
5. Point to "GhostifiedTheme" inside `package.json` in "Ghostified" (look for `dependencies` --> `lyra`)
6. run `npm install --production` to update `package-lock.json`
7. Go to Heroku --> Manual deploy --> Deploy Branch 
8. Your changes will have successfully propagated to production, The Facebook link will have disappeared

This is when things NO longer propagate:

1. Do additional changes to "GhostifiedTheme", like comment out line 36 in `default.hbs` to also remove the Twitter link
2. like previously: Commit changes to "GhostifiedTheme"
3. like previously: run `npm install --production` to update `package-lock.json`
4. this won't make `package-lock.json` point to the latest commit on "GhostifiedTheme", so run `npm update lyra`, `package-lock.json` will now point to the latest commit on "GhostifiedTheme"
4. Go to Heroku --> Manual deploy --> Deploy Branch 
5. Your changes will NO longer propagate to production, The Twitter link will not have disappeared (Please note: the Facebook link has not returned - from the top part of this "To Reproduce" -, it persisted )

**Expected behavior**
Be able to change the theme via my forked theme of a supported Ghost Theme (i.e. Lyra). In other words, to be able to customise "GhostifiedTheme" and have the changes propagate

**How are you deploying this?**
Deployment on Heroku from fork of this repo

**Comment by SNathJr** [comment]
Hey @codechair 
So, my first guess off the top of my head would be that, the deployment script is replacing your edited theme. Maybe you can try removing the theme's dependency from package.json and copy themes shell file as well. Let us know how it goes.

Cheers!
SNathJr

**Comment by codechair** [comment]
Thanks a ton for reverting so quickly @SNathJr 

I get removing the dependency from `package.json`

Can you clarify what you mean with "copy themes shell file as well" please?

**Comment by SNathJr** [comment]
Oh, I am sorry for not being specific. It's the `copy-themes.sh` file in `bin` folder.

**Comment by codechair** [comment]
Thanks and how do I make the contents in `content/themes` be readable?

Changes to them right now do not show up as changes in Github. So I can't commit them

**Comment by SNathJr** [comment]
@codechair Try with the .gitignore file. There would be `content/themes/*`.

**Comment by codechair** [comment]
Super ultra thanks @SNathJr ! Priceless help... 4h of my day ended up rescued by you :)

For others in the future going through the same (just as per suggestion from above from @SNathJr :

1. Remove  "lyra": "github:myforkrepo/lyra-forked", from ` package.json` (obs the path to your theme fork would be here)
2. Remove "lyra" from `copy-themes.sh` file in bin folder.
3. For lyra have the following in your `.gitignore` file (as opposed to `content/themes/*`)
```
content/themes/attila
content/themes/bleak
content/themes/casper
content/themes/london
content/themes/massively
content/themes/pico 
content/themes/the-shell
content/themes/vapor
```

And to follow-up on your final note @SNathJr , sadly the fork only "worked" upon the first `npm install --production` all subsequent changes to the theme did not propagate. See the second part of "To reproduce" in https://github.com/SNathJr/ghost-on-heroku/issues/44#issue-554258437

Or did I misunderstood you with "fork of the theme"?

**Comment by JaneJeon** [comment]
> the fork only "worked" upon the first npm install --production

@codechair well, that would be because, as we say time and time again, Heroku does NOT persist anything locally outside of what's already in your slug.

So the ONLY way to get this to persist every single time would be to just point Lyra (or whatever theme) to _your_ own theme (e.g. `"Lyra": "github:codechair/my-lyra-fork"`), then `copy-themes.sh` will handle the rest.

@SNathJr we've had to repeat ourselves about Heroku not persisting any local file changes (including themes) again and again and again. We really should 1. update "bug" reports template to point anyone regarding this to #9, 2. add documentation, 3. _aggressively_ close any issue about this. Maybe it might also be a good idea to explain in the README how heroku works (only the slug is persisted) and tell people to debug their own stuff (e.g. "if something only works the first time, chances are, it's not part of the slug")

**Comment by codechair** [comment]
Thanks for reverting @JaneJeon, I believe you misunderstood me.

I was pointing all dependencies to my own fork of the theme. So, unsure what you mean?

**Comment by JaneJeon** [comment]
1. You should only need to point _only_ the dependency that you changed into your own fork, so when you say "I was pointing _all_ dependencies" it tells me that you're doing something wrong.
2. It's likely that your reference to your fork ("pointing") was wrong. Where is the forked theme repository and how did you "point" to it in your package.json (give links for both)? I don't believe that you did it correctly, so unless you can show me how exactly you did it I can't help you.

**Comment by codechair** [comment]
@JaneJeon 

Just redid it all again and here it comes: 

- the forked theme: https://github.com/codechair/lyra-forked

- the pointing to the dependency: https://github.com/codechair/ghost-on-heroku/blob/master/package.json

Then the process to lock `package-lock.json` as per https://github.com/SNathJr/ghost-on-heroku/issues/44#issue-554258437 "To reproduce"

**Comment by SNathJr** [comment]
@JaneJeon I believe, @codechair needed help with how the repo works, and how github handles gitignore and gitkeep. 

As far as I understand, @codechair wants to edit lyra theme in their fork and was not able to load it on deploy. 

This was probably because of gitignore file ignoring `content/themes` and replacing it with original theme from tryghost. (@codechair correct me if I am wrong).

The solution was hence to create their own fork of theme with wanted changes and add it to dependencies. Or to add it in the folder manually and remove the code that replaces it.

The scope of this ticket should have been support (not bug).

**Comment by codechair** [comment]
> This was probably because of gitignore file ignoring `content/themes` and replacing it with original theme from tryghost. (@codechair correct me if I am wrong).

@SNathJr the funny part of this is that the original content would not completely override the theme, the changes from the first part of "To reproduce" https://github.com/SNathJr/ghost-on-heroku/issues/44#issue-554258437 would persist on and on, but any new changes would not propagate.

**Comment by SNathJr** [comment]
@JaneJeon Being at work, I believe I did not read that fully and assumed @codechair needed help with replacing the theme with their edited version. 😅

**Comment by JaneJeon** [comment]
@SNathJr funny you should say that, I'm also at work xD

**Comment by codechair** [comment]
Getting back to this issue:

I had solved the issue by reading the theme files directly from my fork of this repo as per kind guidance from @SNathJr .

I'm however struggling with this approach now given I still need to do styling changes in the separate theme (Lyra) fork, then build the `screen.css` and `global.css` with `yarn`, then manually copy those files over to the theme now living in my fork of this repo.

That is a lot of back and forth.

Any chance you'd have any idea on how to actually read from the separate theme fork without suffering from the inconsistencies I've referred on the first comment to this issue?

I'm not opening a new issue since this history is very relevant to why I've moved to using the theme files in the repo.

And as a clean way to replicate what I've mentioned top of this thread:

the forked theme: https://github.com/codechair/lyra-forked

the pointing to the dependency: https://github.com/codechair/ghost-on-heroku/blob/master/package.json

Then the process to lock package-lock.json as per #44 (comment) "To reproduce"

**Comment by SNathJr** [comment]
Hey @codechair 

I am not sure that I understand your question properly. Could you please be a little bit more specific? Maybe give a step by step procedure of what you were doing and what went wrong.

SNathJr

**Comment by codechair** [comment]
Sure @SNathJr , here ir comes:

Describe the bug
I cannot update the theme if:
* theme is in another repo
* the theme is pointed to my fork of this repo as a dependency
* the update that does not propagate is not the first change
* the first change made to the theme persists
(nothing at all, not even a simple removal of the link to Facebook (no html nor css) on footer propagates when it is the second update).

To Reproduce

Fork this repo, let's call the fork "Ghostified"
Fork the theme https://github.com/TryGhost/Lyra, let's call that fork "GhostifiedTheme"
Do first changes like adjusting the footer removing the facebook link (just comment out line 35 in default.hbs) in "GhostifiedTheme"
Commit changes to "GhostifiedTheme"
Point to "GhostifiedTheme" inside package.json in "Ghostified" (look for dependencies --> lyra)
run npm install --production to update package-lock.json
Go to Heroku --> Manual deploy --> Deploy Branch
Your changes will have successfully propagated to production, The Facebook link will have disappeared
This is when things NO longer propagate:

Do additional changes to "GhostifiedTheme", like comment out line 36 in default.hbs to also remove the Twitter link
like previously: Commit changes to "GhostifiedTheme"
like previously: run npm install --production to update package-lock.json
this won't make package-lock.json point to the latest commit on "GhostifiedTheme", so run npm update lyra, package-lock.json will now point to the latest commit on "GhostifiedTheme"
Go to Heroku --> Manual deploy --> Deploy Branch
Your changes will NO longer propagate to production, The Twitter link will not have disappeared (Please note: the Facebook link has not returned - from the top part of this "To Reproduce" -, it persisted )
Expected behavior
Be able to change the theme via my forked theme of a supported Ghost Theme (i.e. Lyra). In other words, to be able to customise "GhostifiedTheme" and have the changes propagate

How are you deploying this?
Deployment on Heroku from fork of this repo

**Comment by JaneJeon** [comment]
Hey @codechair, try working off of this: https://github.com/SNathJr/ghost-on-heroku/tree/always-run-script

Please let me know if it works. My suspicion is that `postinstall` doesn't always run (which we _could've_ verified if you provided us your Heroku build logs), but I know for a fact that Heroku *always* run `build` scripts.
