### ISSUE TITLE
Add stale bot

### ISSUE THREAD

**Issue by JaneJeon** [SNathJr/ghost-on-heroku#45]
Too often, @SNathJr you have to manually close issues when it's already been resolved and the original author doesn't respond.

We should add stalebot to this repo to automatically close out any issues that hasn't had any activity in, say, a week.

Also we should probably add "support" template on top of "bug" template and point anybody who doesn't know what they're doing to the "support" template instead of the bug one. Hell, we might even want to replace "bug" with "support". Thoughts?

**Comment by JaneJeon** [comment]
Also, we should _really_ press anyone who opens an issue to ACTUALLY add details about what they want/what's going wrong.

Exhibit A: https://github.com/SNathJr/ghost-on-heroku/issues/39 
"It's not working" really isn't helpful.

**Comment by SNathJr** [comment]
Agreed @JaneJeon!

Sounds good. We should absolutely do that. But I believe we still should have a bug template along with a new support template added.

**Comment by SNathJr** [comment]
Done and done!

**Comment by aayushdutt** [comment]
The stale bot is adding wontfix and closing non resolved issues (https://github.com/SNathJr/ghost-on-heroku/issues/9)

**Comment by JaneJeon** [comment]
@aayushdutt should be fixed now!
