### ISSUE TITLE
Mailgun have changed their Free Account terms

### ISSUE THREAD

**Issue by valentierra** [SNathJr/ghost-on-heroku#47]
Hi Swastik!

When I tried to add a custom domain to my recently created Mailgun account, it forced me to upgrade. However, once I have introduced my credit card information to proceed, it was rejected in order to make the upgrade directly through Heroku.

On Heroku, I reviewed my app's Resources and found out the next available upgrade is the Concept plan, with 50k emails for US$19/month. That amount of emails is enough for several customers, justifying the use of just one Mailgun account.

Mailgun still offers a more reasonable pay-as-you-go Flex plan for starters, with a tier of free 1000 emails/month (any additional for US$0.80), but it is not available for Mailgun accounts generated from Heroku.    

Regarding this issue, I have a couple of questions:

1 - Is there a way to configure/integrate Ghost-on-Heroku with an external Mailgun account, in order to take advantage of their new Flex and Concept plans?

2 - I found this open-source mail server: [Postal](https://postal.atech.media/). As far as I can see, It requires an Ubuntu 16.04 server, Ruby 2.3, MySQL, RabbitMQ, Node.js and Git. I am not very familiar with Heroku so I would like to have your concept of the feasibility to implement this mail server on Heroku.   

I am considering replacing Mailgun after receiving this email:

[PDF removed as it reveals users email address] -------- transcript below -----

Hi there,

Mailgun is adjusting our plans and pricing to more accurately reflect the value users get from the service and to make room for some great new deliverability features we just released.

Throughout 2019, we were hard at work adding and improving our email capabilities and optimizing our support to help your business grow. While many of these updates were made behind the scenes, the truth is that Mailgun can do a lot more than it could two years ago when we last updated our plans.

What does this mean for you?
On March 1, 2020, we will automatically transition your account to the new Flex plan, a pay-as-you-go plan comparable to the Concept plan you’re currently on. You’ll receive your first invoice under the new plan on April 1 if your amount due is greater than $0.50. According to your usage in December, your invoice under the new price per message of $0.0008 would have been $0 for December. It’s a modest change, but we wanted to be transparent about it.

What’s changing with the Flex plan?
Flex offers you the same pay-per-use model you were used to on the Concept plan. The main differences are that we are no longer offering 10,000 free emails or 100 free validations per month, and our support options now include limited ticket support as well as enhanced self-service Q&As so you can find answers faster. Additionally, while your existing routes will still be functional, new routes will not be supported on this plan.

What other options do I have?
We have several other plans available with additional features and service levels, including a new subscription plan called Foundation that starts at $35 per month. This plan provides access to new deliverability tools like Inbox Placement so you can effortlessly increase your deliverability and email ROI.

Looking for validations, inbound routing, or more support? Foundation is a great starter plan. If this is something you’re interested in, check out your plan options.

We’ll send a couple more reminders between now and March 1st, but if you have any questions about what this means for you, we’re here to help. Please submit a support ticket, and we’ll follow up with you shortly.

Best,
The Mailgun Team

**Comment by JaneJeon** [comment]
I would refer to @SNathJr for question 1, but as for question 2, I can answer this because I tried it myself:

_DO. NOT. SELF. HOST. MAIL. SERVERS._

Getting the software stack up and running is one thing, getting it to _actually_ deliver to your recipients' spam box, let alone their inbox is a WHOLE different game that you do NOT want to mess with.

imho Mailgun is utter crap compared to Sendgrid, so if Mailgun is failing you I suggest you make a Sendgrid account (which, from my experience, also has a lot better deliverability but that's besides the point) and find a way to hook that instead.

**Comment by SNathJr** [comment]
Hey @valentierra,

Answering your question 1 here.

Off the top of my head, this just might work. Go to Heroku > your blog's app > settings > reveal config vars. And you will see something like this.
![image](https://user-images.githubusercontent.com/20180524/74090894-032e2000-4ad7-11ea-8c17-45c2ca8418d3.png)

Next, replace all mailgun credentials with your mailgun account's credentials. You may want to Heroku-generated mailgun account's domain and create a domain (and verify it).

**Comment by valentierra** [comment]
@JaneJeon and @SNathJr, Thank you both!

Pretty fair answers! I'll give a try to both suggestions (Mailgun reconfiguration and Sendgrid setup).

Closing this issue ipso facto!

**Comment by valentierra** [comment]
Hi There!

Mailgun's flex plan configured apart from the Heroku's add-on was easy to implement. I also tried Sendgrid add-on on Heroku and its configuration was even easier. 

As far as I can see, Ghost has integrated Mailgun as its solely-preferred solution for sending emails. Mailgun's Flex plan seems to provide a reasonable free solution for sending emails from Ghost. Nevertheless, receiving emails from customed domains is no longer possible as Flex doesn't allow email routing. As this feature is the missing part, do you know any email routing service that may be integrated to provide the former Heroku-on-Ghost features?

**Comment by JaneJeon** [comment]
> Ghost has integrated Mailgun as its solely-preferred solution for sending emails

Ghost uses nodemailer under the hood, which supports *all* SMTP transports. See here: https://ghost.org/docs/concepts/config/#mail

So you can configure whatever mail provider you want as long as you have an SMTP credentials with them. For example, if you wanted to use SendGrid, you could set the following environment variables to override Ghost's default email settings:

```
mail__options__service=sendgrid
mail__options__auth__user=$yourSMTPCredentialsUsername
mail__options__auth__pass=$yourSMTPCredentialsPassword
```

The magic of configuration here is that nodemailer's already knows the default configuration for most `service`s (including Mailgun and SendGrid and basically every SMTP provider under the sun) so just setting `mail__options__service` and the appropriate credentials should be enough to hook it up.

**Comment by valentierra** [comment]
@JaneJeon Thank you!

I dare to give that affirmation based on what is said at the end of this thread: 
[Sendgrid email configuration](uhttps://forum.ghost.org/t/sendgrid-email-configuration/10896/4)

But you are right, the current architecture suggests another thing. Hopefully, they will keep the platform-neutral regarding the mail provider.

For the incoming email routing service, I couldn't find a free option, so I'll give a try using an own machine with Postal, iRedMail and Kolab.

**Comment by JaneJeon** [comment]
@valentierra yeah, as far as I know there is no "bulk send" interface for SMTP protocol. Didn't know Ghost had a custom hack just for Mailgun :/

As for receiving emails, I think both Mailgun and SendGrid (and any other "big" email provider) support inbound emails.

**Comment by valentierra** [comment]
@JaneJeon, I hope Ghost guys changed their minds. I like Sendgrid. I also found quite interesting similar services using blockchain (e.g. EmailOctopus).

Yes, you are right. Mailgun and Sendgrid support inbound emails. The problem is that we need a UI for no-technical users so they can create and route their email accounts by themselves.
