### ISSUE TITLE
Change the database

### ISSUE THREAD

**Issue by gerardogrimaldi** [SNathJr/ghost-on-heroku#49]
**Describe your problem**
I can't make another database work.

**Describe the things you have tried so far**
I changed the database in the environment variables, the variables in the deploy, I even deployed in one click with a fork on the other database MYSQL_DATABASE_URL.

**Have you checked for similar issues?**
Yes, no issue about it.

**Additional context**
The error I get when the app its creating the tables is ...

Mar 27 08:38:54 literalmente heroku/web.1 State changed from starting to crashed
Mar 27 08:38:54 literalmente heroku/web.1 Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
Mar 27 08:38:54 literalmente heroku/web.1 Stopping process with SIGKILL
Mar 27 08:38:54 literalmente heroku/web.1 Process exited with status 137
Mar 27 08:38:56 literalmente heroku/router at=error code=H10 desc="App crashed" method=GET path="/" host=literalmente.herokuapp.com request_id=3d02878d-acbb-4581-883c-3e0649312dc0 fwd="181.47.85.18" dyno= connect= service= status=503 bytes= protocol=https

**Comment by JaneJeon** [comment]
I'm sorry, it's hard to understand what you're trying to do here. Are you saying you're having trouble swapping out for a different database? Then you should set `DATABASE_URL` and _not_ `MYSQL_DATABASE_URL`.
