### ISSUE TITLE
How to customize the deployed app

### ISSUE THREAD

**Issue by n-kode** [SNathJr/ghost-on-heroku#50]
I tried deploying the app and it works fine, I am just wondering how could I customized the deployed app locally then will push the changes to heroku. I tried to clone the heroku git url but it says 'empty repository', Any help on this. Thanks!

**Comment by cmorbitzer** [comment]
@n-kode Try adding `heroku` as a remote repository and then pushing to `heroku master`

```
git remote add heroku [URL]
git push heroku master
```

**Comment by n-kode** [comment]
@cmorbitzer Yup I was able to push some test commit using git push heroku master but what I mean is to customize the app like for example edit the css, themes etc.  What I can see in content/theme folder is just a ,gitkeep file, please educate me on this :)
Can I also do npm install and run this in my local machine. Thanks!

**Comment by cmorbitzer** [comment]
The themes are copied in from separate repositories. You'll have to fork the theme you need, customize it, and then change `package.json` to point the theme package at your fork instead of the original.

**Comment by n-kode** [comment]
@cmorbitzer  got it. Thanks!
