### ISSUE TITLE
Sendgrid no longer an SMTP option?

### ISSUE THREAD

**Issue by boxedpaul** [SNathJr/ghost-on-heroku#55]
I started a new ghost blog on Heroku a few months ago. For email, I changed the configuration to Sendgrid as I already have an account.

I've created a new blog, but I can't find any information on how to set up Sendgrid for the new blog. It's like the info has been scrubbed from the internet!!

Has something changed that means using Sendgrid is no longer possible?

Thanks for any help you can provide.

**Comment by JaneJeon** [comment]
I don't think Ghost supports Sendgrid in any official capacity. I suggest you just manually hook it up as an SMTP provider. Just google "ghost email SMTP" or something, because that generic SMTP transport *should* work also for Sendgrid.

**Comment by JaneJeon** [comment]
Actually, just look at the pinned issue. You can find more information there.
