### ISSUE TITLE
How to point "My Site" to my domain instead of localhost?

### ISSUE THREAD

**Issue by talesmgodois** [SNathJr/ghost-on-heroku#56]
After I click to see my site I get the following result:
![image](https://user-images.githubusercontent.com/3044796/90297018-9d469a80-de63-11ea-8dc9-efc2eb70b582.png)

If I see the url, the link tries to open I get: http://localhost:2368/. I already have deployed my app and configured my domain and s3 bucket. But I still getting this localhost error. Shouldn't this go to my blog url: http://blog.startupshare.xyz ?

I saw that I can change this configuration in the code. But, I couldn't find this on  https://github.com/SNathJr/ghost-on-heroku , And I don't know how the heroku button knows which repository to use. I would like to have control on how to update my heroku project deployed using heroku button, but I could not figure out how.

Can somebody help me?

**Comment by JaneJeon** [comment]
Can you share your `APP_PUBLIC_URL` environment/config variable in heroku? You say "I already have deployed my app and configured my domain" but the admin literally just points to `APP_PUBLIC_URL`, so I'm guessing your `APP_PUBLIC_URL` either does not exist or that the server somehow has not picked up the variable yet (in which case, try restarting it)

**Comment by talesmgodois** [comment]
SO, I really haven't had this before @JaneJeon. But, After setting this var, my blog is getting the following error:
It's having a "redirect loop"

![image](https://user-images.githubusercontent.com/3044796/90313208-0ddfcc80-dee1-11ea-9d56-5e2e6dc3b0e0.png)

**Comment by JaneJeon** [comment]
Hmm, interesting. I have my `APP_PUBLIC_URL` set to `https://janejeon.dev`. Emphasis on the `https://`. Can you try setting `APP_PUBLIC_URL` to `https://blog.startupshare.xyz`?

If that doesn't work, I'll have to assume it is a problem with Ghost-Admin looking at WWW.startupshare.xyz and not BLOG.startupshare.xyz.

**Comment by talesmgodois** [comment]
That's something that I'd like to understand. How the button does work? Is it possible to point to my own forked repoistory?

**Comment by JaneJeon** [comment]
1. Did the `https://` solution work for you?
2. If not, did you open an issue on ghost-admin regarding subdomains?
3. What would you like to understand?

The "button" is literally just a hyperlink - Heroku is the one that's doing all the magic (it picks up your repo by looking at the referrer for the request), so if you were to fork your own repo, the button would still work for you.

**Comment by NandiyaLive** [comment]
Hi @talesmgodois, I'm having this issue too and I saw that yours is now working fine. How did you fix it?

**Comment by JaneJeon** [comment]
@NandiyaLive did you try the suggestions I gave in this thread?

**Comment by NandiyaLive** [comment]
@JaneJeon I tried `https` but it didn't work. But didn't open a issue on ghost admin

**Comment by JaneJeon** [comment]
@NandiyaLive could you try opening an issue with ghost-admin instead? All we do with `ghost-on-heroku` is to tweak the application to be host-able by Heroku (mainly getting around the ephemeral file system), it does not touch ghost-admin in any way.

**Comment by NandiyaLive** [comment]
@JaneJeon I think there's no problem with ghost cause it's working with the herokuapp.com URL only problem is it's not working properly with custom URLs

**Comment by talesmgodois** [comment]
Actually I gave up man. In the future I plan to use docker instead of this way of deploy. I really think this might be a problem with ghost @NandiyaLive. Looks like some of these urls are hardcoded, and this is generating the problem. So, My partial solution is the beginning case of this question. I keep not seeing my site at that menu. Looks like I would need to change it in the code to solve this issue, and I don't know how to do it with the heroku deploy button. So, when I change to docker I can set my own fork, and change it how I want. This is my plan to the future. I just have two posts in the blog and I am working on the third one right now. So, Sorry I am unable to help you =/

**Comment by NandiyaLive** [comment]
@talesmgodois okay no problem. if you found any solution please share it with me :)
@JaneJeon please fix this error if you can do it in your side.
