### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by Richi2293** [SNathJr/ghost-on-heroku#6]
![image](https://user-images.githubusercontent.com/5848941/58268465-c4f4a300-7d85-11e9-9021-46d094fe23d9.png)

I think the file "yarn.lock" has to be removed to make it work

**Comment by SNathJr** [comment]
I have deleted the yarn.lock now. Please verify if the build succeeds now.

**Comment by Richi2293** [comment]
Yes I forked the repository, deleted the yarn.lock file, tried again to deploy and it worked

**Comment by SNathJr** [comment]
Thank you for confirming, I will close this issue now.
