### ISSUE TITLE
Updating Ghost to 3.41.5

### ISSUE THREAD

**Issue by rohitgehe05** [SNathJr/ghost-on-heroku#68]
**Describe your problem**
When I try to run the following commands:
```
npm upgrade ghost
git add package.json package-lock.json
git commit -m 'Update dependencies'
git push heroku master
```
I am not able to get a successful build when I push to Heroku

**Describe the things you have tried so far**
I've tried searching how to resolve the conflicts but to no avail. I think there is an issue with some of the theming
Attaching the build log
```
-----> Installing dependencies
       Installing node modules
       npm ERR! Error while executing:
       npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/sethlilly/Vapor.git
       npm ERR! 
       npm ERR! Host key verification failed.
       npm ERR! fatal: Could not read from remote repository.
       npm ERR! 
       npm ERR! Please make sure you have the correct access rights
       npm ERR! and the repository exists.
       npm ERR! 
       npm ERR! exited with error code: 128
```

**Have you checked for similar issues?**
Yes, couldn't find any on this repo or the Ghost repo

**Comment by carlosmgahete** [comment]
I had the same issue.

I solved it by downgrading to npm version 6.14.11 since it is the one used by Heroku

To downgrade just run:

`npm i -g npm@6.14.11`

**Comment by rohitgehe05** [comment]
thanks @carlosmgahete do i downgrade npm first before upgrading ghost or vice versa?

**Comment by carlosmgahete** [comment]
Yes, first downgrade npm, and then update ghost and push to Heroku.
